# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'ubuntu-agent'
  vmImage: ubuntu-latest

steps:
- script: newman run DeskDevice.postman_collection.json -e Desk.postman_environment.json -r htmlextra
  displayName: 'desk device apis'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
