# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'ubuntu-agent'
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'npm install -g newman'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: CmdLine@2
  inputs:
    script: 'npm install -g newman-reporter-htmlextra'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: CmdLine@2
  inputs:
    script: 'newman run DeskDevice.postman_collection.json -e Desk.postman_environment.json -r htmlextra'
    workingDirectory: 'Gibaa34/Postman'
    failOnStderr: true
